apiVersion: v1
kind: Template
labels:
  application: flumeapp
  createdby: flume-testing-template
message: This is a simple Apache Flume template for testing
metadata:
  annotations:
    description: 'This tier1 Apache Flume template is an example of Flume
      with syslog source and file_role sink.

      WARNING: Only use this template for testing'
    tags: bigdata,flume-test
  creationTimestamp: null
  name: flume-syslog-to-file
objects:
#
# Layer 1: Builds
# 
# This layer defines all the builds we will require for our application.
#
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: flume-build
  spec:
    runPolicy: "Serial"
    triggers:
      - type: "ConfigChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/bigcontainer/bigcont"
        ref: "flume-service"
      contextDir: "flume"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: "Dockerfile.centos7"
    output:
      to:
        kind: "ImageStreamTag" 
        name: "flume-service:latest"
#
# Layer 2: Images
# 
# This layer defines all the images produced by the builds.
#
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: "flume-service"
#
# Layer 3: Deployments
#
# This layer defines the core of our applications. It defines what will be
# running in OpenShift:
#
# - A replication controller template: What will be deployed.
# - The default replica count for the deployment: How many instances will be
#   deployed and running.
# - A deployment strategy which will be used to execute the deployment: How it
#   will be deployed
# - A set of triggers which cause deployments to be created automatically:
#   When and Why will it be deployed.
#
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${FLUME_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${FLUME_SERVICE_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${FLUME_SERVICE_NAME}
      spec:
        containers:
        - image: "flume-service"
          name: "flume"
          ports: 
          - containerPort: 8080
            protocol: "TCP"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: ${FLUME_SERVICE_NAME}
    triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "flume"
        from:
          kind: ImageStreamTag
          name: ${FLUME_IMAGE_STREAM_TAG}
    strategy:
      type: Recreate
    paused: false
    revisionHistoryLimit: 2
#
# Layer 4: Abstractions
#
# This layer defines all of the additional resources needed for our application
# to run: Service, Route, ServiceAccount, PVC, etc.

#
# Service Account
#
#- apiVersion: v1
#  kind: ServiceAccount
#  metadata:
#    name: ${FLUME_SERVICE_NAME}
#
# Route
#
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${FLUME_SERVICE_NAME}
  spec:
    host: flume-tier1.cloudapps.redhat.lan
    to:
      kind: Service
      name: ${FLUME_SERVICE_NAME}
#
# Role Binding
#
#- apiVersion: v1
#  groupNames: null
#  kind: RoleBinding
#  metadata:
#    name: ${FLUME_SERVICE_NAME}_edit
#  roleRef:
#    name: edit
#  subjects:
#  - kind: ServiceAccount
#    name: ${FLUME_SERVICE_NAME}
#
# Service
#
- apiVersion: v1
  kind: Service
  metadata:
    name: ${FLUME_SERVICE_NAME}
  spec:
    ports:
    - name: agent
      port: 5140
      protocol: TCP
      targetPort: 50000
    selector:
      name: ${FLUME_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
#
# Posible Template parameters to override
#
parameters:
- description: The name of the OpenShift Service exposed for the Apache Flume container.
  displayName: Apache Flume Service Name
  name: FLUME_SERVICE_NAME
  value: "flume"
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: "512Mi"
- description: Name of the ImageStreamTag to be used for the Apache Flume image.
  displayName: Apache Flume ImageStreamTag
  name: FLUME_IMAGE_STREAM_TAG
  value: "flume-service:latest"
