apiVersion: v1
kind: Template
labels:
  template: flume-testing-template
message: This is a simple Apache Flume template for testing
metadata:
  annotations:
    description: 'This tier1 Apache Flume template is an example of Flume
      with syslog source and file_role sink.

      WARNING: Only use this template for testing'
    tags: bigdata,flume-test
  creationTimestamp: null
  name: flume-syslog-to-file
objects:
#
# Build
#
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: flume-build
  spec:
#
# Deployment Config
#
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${FLUME_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${FLUME_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${FLUME_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: 'true'
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 3
          name: jenkins
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: ${FLUME_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: ${FLUME_SERVICE_NAME}
        volumes:
        - emptyDir:
            medium: ''
          name: ${FLUME_SERVICE_NAME}-data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: ${FLUME_IMAGE_STREAM_TAG}
          namespace: ${NAMESPACE}
        lastTriggeredImage: ''
      type: ImageChange
    - type: ConfigChange
#
# Service Account
#
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${FLUME_SERVICE_NAME}
#
# Route
#
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${FLUME_SERVICE_NAME}
  spec:
    host: flume-alias.cloudapps.redhat.lan
    to:
      kind: Service
      name: ${FLUME_SERVICE_NAME}
#
# Role Binding
#
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: ${FLUME_SERVICE_NAME}_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${FLUME_SERVICE_NAME}
#
# Service
#
- apiVersion: v1
  kind: Service
  metadata:
    name: ${FLUME_SERVICE_NAME}
  spec:
    ports:
    - name: agent
      port: 5140
      protocol: TCP
      targetPort: 50000
    selector:
      name: ${FLUME_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
#
# Template parameters to override
#
parameters:
- description: The name of the OpenShift Service exposed for the Apache Flume container.
  displayName: Apache Flume Service Name
  name: FLUME_SERVICE_NAME
  value: flume
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi
- description: The OpenShift Namespace where the Apache Flume ImageStream resides.
  displayName: Apache Flume ImageStream Namespace
  name: NAMESPACE
  value: openshift
- description: Name of the ImageStreamTag to be used for the Apache Flume image.
  displayName: Apache Flume ImageStreamTag
  name: FLUME_IMAGE_STREAM_TAG
  value: flume:latest
